####################################################
#                                                  #
#                  Basic Settings                  #
#                                                  #
####################################################

###  Global configuration  ###
homeassistant:
  name: Home
  latitude: !secret home_loc_lat
  longitude: !secret home_loc_long
  elevation: 101
  temperature_unit: F
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customized.yaml

###  Zones  ###
zone:
  name: Home
  latitude: !secret home_loc_lat
  longitude: !secret home_loc_long
  radius: 275
  icon: mdi:home

zone 2:
  name: Store
  latitude: !secret store_loc_lat
  longitude: !secret store_loc_long
  radius: 125
  icon: mdi:shopping
  
###  MQTT  ###
mqtt:
  broker: localhost
  port: 1883
  client_id: HomeAssistant-master
  username: !secret mqttuser
  password: !secret mqttpassword
  keepalive: 60

###  Lockitron  ###
lock:
  platform: lockitron  
  access_token: !secret lockitron_key
  id: !secret lockitron_id
  
###  Z-Wave  ###
zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/lib/python3.4/site-packages/libopenzwave-0.3.2-py3.4-linux-armv7l.egg/config

##  Emulated Hue Bridge  ###
emulated_hue:
  host_ip: 192.168.2.216
  type: alexa
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: true
  exposed_domains:
    - switch
    - light

###  HTTP  ###
http:
  api_password: !secret http_password
  ssl_certificate: !secret sslcert
  ssl_key: !secret sslkey

### IFTTT  ###
ifttt:
  key: !secret ifttt_key
  
###  BloomSky  ###
bloomsky:
  api_key: !secret bloomsky_api

###  Garadget  ###
cover:
  platform: garadget
  covers:
      290058001151353338363333:
        username:  !secret garage_user
        password:  !secret garage_password
        name:  Garage Door

###  NEST  ###
nest:
  client_id: !secret nest_client
  client_secret: !secret nest_secret

climate:
  platform: nest

###  Harmony Remote  ###
#remote:
#  platform: harmony
#  name: Livingroom
#  host: 192.168.2.124

### SmartThings Home Alarm ###
alarm_control_panel:
  - platform: manual
    name: house_alarm

    
###  Octoprint   ###
octoprint:
  host: 192.168.2.185
  api_key: 25AC7E14973E483D821E9E84069496E4
  

####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################

###  Devices  ###
device_tracker: !include devices/device_trackers.yaml
media_player: !include devices/media_players.yaml
camera: !include devices/cameras.yaml
switch: !include devices/switches.yaml
sensor: !include devices/sensors.yaml
light: !include devices/light.yaml

###  Logger  ###
#logger: !include logger.yaml

###  Groups  ###
group: !include groups.yaml

###  Scenes  ###
scene: !include scenes.yaml

###  Scripts  ###
script: !include scripts/scripts.yaml

###  Automation  ###
automation: !include_dir_merge_list automation

###  Notification  ###
notify: !include notify.yaml

###  Weblinks  ###
weblink: !include weblink.yaml

###  Input Boolean  ###
input_boolean: !include input_boolean.yaml

###  Configuration Panel  ###
config:

####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################

###  Sun  ###
sun:

###  Logbook  ###
logbook:
  exclude:
    entities:
      - sensor.garage_door_time_in_state
      - sensor.garage_door_wifi_signal_strength

###  SSL Renew  ###
shell_command: 
  renew_ssl: ~/certbot/certbot-auto renew --quiet --no-self-upgrade --standalone --preferred-challenges http-01

###  History  ###
history:

###  Recorder  ###
recorder:
  purge_days: 30
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun

###  Frontend  ###
frontend:
  
### Voice Commands  ###
conversation:

###  Updater  ###
updater:

###  Discovery  ###
discovery:
