- platform: owntracks

- platform: mqtt
  qos: 1
  devices:
    george_phone: !secret tracker_george
    michelle_phone: !secret tracker_michelle
    
- platform: tomato
  host: 192.168.2.1
  username: !secret router_admin
  password: !secret router_password
  http_id: !secret router_httpid