###  Livingroom Kodi Player  ###
- platform: kodi
  host: 192.168.2.127
  port: 8080
  name: Livingroom Player
  username: !secret living_kodi_username
  password: !secret living_kodi_password
  
###  Master Bedroom Kodi Player  ###
- platform: kodi
  host: 192.168.2.189
  port: 8383
  name: Office Player
  username: !secret office_kodi_username
  password: !secret office_kodi_password

###  Google Play Media Desktop  ###  
- platform: gpmdp
  host: !secret house_ip
  name: Music

- platform: cast

###  Office TV  ###
- platform: vizio
  host: 192.168.2.7
  access_token: lcypdq2kfa