- platform: bloomsky
  scan_interval: 120
  name: Weather


- platform: speedtest
  hour:
    - 6
    - 18
  monitored_conditions:
    - ping
    - download
    - upload
    
  
- platform: thinkingcleaner


- platform: template
  sensors:
    garage_door_status:
      friendly_name: 'Garage Door'
      value_template: '{{ states.cover.garage_door.state }}'
    garage_door_time_in_state:
      friendly_name: 'Since'
      value_template: '{{ states.cover.garage_door.attributes["time in state"] }}'
    garage_door_wifi_signal_strength:
      friendly_name: 'WiFi strength'
      value_template: '{{ states.cover.garage_door.attributes["wifi signal strength (dB)"] }}'
      unit_of_measurement: 'dB'
    sensative_strips_sensor_2_0_cleaned:
      friendly_name: 'Garage Entrance'
      value_template: "{{ 'closed' if is_state('binary_sensor.sensative_strips_sensor_2_0', 'off') else 'open' }}"
    sensative_strips_sensor_3_0_cleaned:
      friendly_name: 'Back Door'
      value_template: "{{ 'closed' if is_state('binary_sensor.sensative_strips_sensor_3_0', 'off') else 'open' }}"
    garage_door_status_cleaned:
      friendly_name: 'Garage Door'
      value_template: '{{ states.cover.garage_door.state }}'
    aeotec_zw100_multisensor_6_burglar_5_10_cleaned:
      friendly_name: 'Living Room Motion Detector'
      value_template: "{{ 'Motion' if is_state('sensor.aeotec_zw100_multisensor_6_burglar_5_10', '8') else 'No motion' }}"