- platform: wake_on_lan
  mac_address: "D4:3D:7E:C0:0D:2C"
  name: "Main_PC_WOL"
  host: "192.168.2.202"

- platform: command_line
  switches:
    pc:
      command_on: " "
      command_off: "net rpc shutdown -I 192.168.2.202 -U kodi%kodi"
        
- platform: template
  switches:
    pccopy:
      value_template: '{{ states.switch.Main_Pc_Wol.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.Main_Pc_Wol
      turn_off:
        service: switch.turn_off
        entity_id: switch.pc


- platform: thinkingcleaner

- platform: command_line
  switches:
    office_tv:
      friendly_name: Office TV
      command_on: "/usr/bin/curl -k -H \"Content-Type: application/json\" -H \"AUTH: lcypdq2kfa\" -X PUT -d '{\"KEYLIST\": [{\"CODESET\": 11,\"CODE\": 1,\"ACTION\":\"KEYPRESS\"}]}' https://192.168.2.13:9000/key_command/"
      command_off: "/usr/bin/curl -k -H \"Content-Type: application/json\" -H \"AUTH: lcypdq2kfa\" -X PUT -d '{\"KEYLIST\": [{\"CODESET\": 11,\"CODE\": 0,\"ACTION\":\"KEYPRESS\"}]}' https://192.168.2.13:9000/key_command/"
      command_state: "/usr/bin/curl -k -H \"Content-Type: application/json\" -H \"AUTH: lcypdq2kfa\" -X GET https://192.168.2.13:9000/state/device/power_mode"
      value_template: >
        {% if value_json.ITEMS.0.VALUE == 1 %}
          true
        {% else %}
          false
        {% endif %}